Algoritmo "Exemplo Laco Para"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor  : Jailson Costa dos Santos
// Descrição  : Aqui você descreve o que o programa faz! (função)
// Autor(a)   : Murilo
// Data atual : 03/09/2021
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 1 ate 10 passo 1 faca
      Escreval("Teste.")
   fimpara

Fimalgoritmo