Algoritmo "Exercicio11DiasVividos"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Escreva um algoritmo para ler as dimensões de um triângulo (base e altura), calcular e escrever a área do triângulo.
// Autor(a) : Jailson
// Data atual : 24/08/2021
Var
// Seção de Declarações das variáveis
anos,meses,dias,vida:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Fimalgoritmo