Algoritmo "LacoRepeticaoEnquanto"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Murilo
// Data atual  : 01/09/2021
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contadora<10 faca
      Escreval("Item da lista")
      contadora<-contadora+1
   fimenquanto
   
Fimalgoritmo