Algoritmo "multiplicacao"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Murilo
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
multiplicacao:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero:")
Leia("")

Fimalgoritmo