Algoritmo "Soma"
// Disciplina  : [Java Script e Lógica de Programação]
// Professor   : Professor Obama
// Descrição   : Soma de dois valores e apresentação do resultado
// Autor(a)    : Murilo
// Data atual  : 24/08/2021
Var
numero01:inteiro
numero02:inteiro
soma:inteiro




Inicio
Escreval("Digite  um valor: ")
leia(numero01)
Escreval("Digite outro valor: ")
leia(numero02)
soma<-numero01+numero02
Escreval("O resultado da soma desses dois valores é: ",soma)




Fimalgoritmo